from aiogram.types import ReplyKeyboardMarkup, KeyboardButton,InlineKeyboardMarkup,InlineKeyboardButton



# ___Main_menu___
btnStart = KeyboardButton('Старт')
btnOther = KeyboardButton('Info')
btnHelp = KeyboardButton('Инструкция')
mainMenu = ReplyKeyboardMarkup(resize_keyboard=True).add(btnStart,btnOther,btnHelp)


# ___Other menu___

btnYes = KeyboardButton('Да')
btnNO = KeyboardButton('Нет')
btnmainMenu = KeyboardButton('Главное меню')
btnname = KeyboardButton ('/Изменить_имя')
btncontact = KeyboardButton ('Отправить контакт',request_contact=True)
contactmenu = ReplyKeyboardMarkup(resize_keyboard=True).add(btncontact)
otherMenu = ReplyKeyboardMarkup(resize_keyboard=True).add(btnYes,btnNO,btnmainMenu)
namemenu = ReplyKeyboardMarkup(resize_keyboard=True).add(btnname)
# otherMenudel = ReplyKeyboardRemove(resize_keyboard=True).add(btnYes,btnNO,btnmainMenu)
# ___qwestions menu___
btnqwestion_1=KeyboardButton('Вопрос №1')
btnqwestion_2=KeyboardButton('Вопрос №2')
btnqwestion_3=KeyboardButton('Вопрос №3')
btnqwestion_4=KeyboardButton('Вопрос №4')
btnqwestion_5=KeyboardButton('Вопрос №5')
btnqwestion_6=KeyboardButton('Вопрос №6')
btnqwestion_7=KeyboardButton('Вопрос №7')
btnqwestion_8=KeyboardButton('Вопрос №8')
btnqwestion_9=KeyboardButton('Вопрос №9')
btnqwestion_10=KeyboardButton('Вопрос №10')
btnqwestion_11=KeyboardButton('Вопрос №11')
btnqwestion_12=KeyboardButton('Вопрос №12')
btnqwestion_13=KeyboardButton('Вопрос №13')
btnqwestion_14=KeyboardButton('Вопрос №14')
btnqwestion_15=KeyboardButton('Вопрос №15')
btnqwestion_16=KeyboardButton('Вопрос №16')
btnqwestion_17=KeyboardButton('Вопрос №17')
btnqwestion_18=KeyboardButton('Вопрос №18')
btnqwestion_19=KeyboardButton('Вопрос №19')
btnqwestion_20=KeyboardButton('Вопрос №20')
btnqwestion_21=KeyboardButton('Вопрос №21')
btnqwestion_22=KeyboardButton('Вопрос №22')
btnqwestion_23=KeyboardButton('Вопрос №23')
btnqwestion_24=KeyboardButton('Вопрос №24')
btnqwestion_25=KeyboardButton('Вопрос №25')
btnqwestion_26=KeyboardButton('Вопрос №26')
btnqwestion_27=KeyboardButton('Вопрос №27')
btnqwestion_28=KeyboardButton('Вопрос №28')
btnqwestion_29=KeyboardButton('Вопрос №29')
btnqwestion_30=KeyboardButton('Вопрос №30')

btnmainMenu = KeyboardButton('Главное меню')
btndownloadVideo = KeyboardButton('/Видеоответ')

downloadVideo = ReplyKeyboardMarkup(resize_keyboard=True).add(btndownloadVideo)
qwestionMenu = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_1, btnmainMenu)
qwestionMenu.add(btnname)
qwestionMenu_2 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_2, btnmainMenu)
qwestionMenu_3 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_3,  btnmainMenu)
qwestionMenu_4 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_4,  btnmainMenu)
qwestionMenu_5 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_5,  btnmainMenu)
qwestionMenu_6 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_6,  btnmainMenu)
qwestionMenu_7 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_7,  btnmainMenu)
qwestionMenu_8 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_8,  btnmainMenu)
qwestionMenu_9 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_9,  btnmainMenu)
qwestionMenu_10 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_10, btnmainMenu)
qwestionMenu_11 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_11,  btnmainMenu)
qwestionMenu_12 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_12,  btnmainMenu)
qwestionMenu_13 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_13,  btnmainMenu)
qwestionMenu_14 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_14,  btnmainMenu)
qwestionMenu_15 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_15,  btnmainMenu)
qwestionMenu_16 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_16,  btnmainMenu)
qwestionMenu_17 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_17,  btnmainMenu)
qwestionMenu_18 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_18,  btnmainMenu)
qwestionMenu_19 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_19,  btnmainMenu)
qwestionMenu_20 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_20,  btnmainMenu)
qwestionMenu_21 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_21,  btnmainMenu)
qwestionMenu_22 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_22,  btnmainMenu)
qwestionMenu_23 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_23,  btnmainMenu)
qwestionMenu_24 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_24,  btnmainMenu)
qwestionMenu_25 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_25,  btnmainMenu)
qwestionMenu_26 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_26,  btnmainMenu)
qwestionMenu_27 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_27,  btnmainMenu)
qwestionMenu_28 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_28,  btnmainMenu)
qwestionMenu_29 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_29,  btnmainMenu)
qwestionMenu_30 = ReplyKeyboardMarkup(resize_keyboard=True).add(btnqwestion_30,  btnmainMenu)

# ________Admin menu___
list_qwestions = KeyboardButton('/Получить_список_вопросов')
get_interview = KeyboardButton('/Получить_видеоответы')
create_qwestion = KeyboardButton('/Загрузка_вопроса')
delete_qwestion = KeyboardButton('/Удалить_вопрос')
admin_menu = ReplyKeyboardMarkup(resize_keyboard=True).add(get_interview, create_qwestion)
admin_menu.add(list_qwestions)
admin_menu.add(delete_qwestion)
# Новое меню вопросов
btngetqwestions = KeyboardButton('/getqwestions')
getqwestions = ReplyKeyboardMarkup(resize_keyboard=True).add(btngetqwestions)